server:
  port: 8080

spring:
  application:
    name: rabbitmq-vs-kafka-lab
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    org.springframework.amqp: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} %-22logger{0} %msg%n"
